# Generated by Django 4.1.5 on 2023-04-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('active', models.BooleanField()),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
